Call RunAction("Login #1", oneIteration)
Call RunAction("Create New Order #2", oneIteration)
Call RunAction("Bitmap Check #3", oneIteration)
Call RunAction("Flights Button Check Disabled #4", oneIteration)
Call RunAction("Flights Button Check Enable #5", oneIteration)
Call RunAction("Insert Button Check Enabled #6", oneIteration)
Call RunAction("Default Ticket #7", oneIteration)
Call RunAction("Default Class Check #8", oneIteration)
Call RunAction("Insert Button disabled #9", oneIteration)